# Generated by Django 3.1.14 on 2022-12-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20221226_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
    ]
